// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutoremoveController from "./autoremove_controller";
application.register("autoremove", AutoremoveController);

import TimerController from "./timer_controller";
application.register("timer", TimerController);
